### ISSUE TITLE
Set page timeouts to prevent browser freezing.

### ISSUE THREAD

**Issue by greebie** [archivesunleashed/auk#191]
**Is your feature request related to a problem? Please describe.**
This is related to issue #189 - some files are too large and cause problems with page loading.  While that specific problem can be resolved in GraphPass, the broader issue of browser crashing may be something we desire, especially given different computer clients and so on.

**Describe the solution you'd like**
AUK should:
- set an appropriate page timeout on load.
- identify the related problem (eg. gexf file too large, other errors).
- render the page, and if its not a big error, simply explain to the user what caused the timeout.

**Describe alternatives you've considered**
Apparently, [Ruby's Timeout::timeout(s) class is dangerous and should not be used.](https://medium.com/@adamhooper/in-ruby-dont-use-timeout-77d9d4e5a001). I am not sure if Rubocop will give a warning on this either.

**Additional context**

**Comment by greebie** [comment]
I got the idea that the *real* problem here is that graph.js is storing data in the dom instead of calling from http. I had trouble making it work without doing so, but that may have just been a mental block.

I am going to try and see if I can get sigma to run the gexf via a url instead of the dom. In theory, this should reduce the amount of load on the browser. It would also move the timeout problems to javascript.

If I can, I am going to close this issue or perhaps re-name it to reflect the new approach. If not, I'll revisit the ruby timeout idea.

**Comment by ianmilligan1** [comment]
Closed as per discussion in #189.
