### ISSUE TITLE
Update Docs to Include Full-Text Filtering

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/auk#202]
With #197 closed, we now need to update the documentation to include the new button. We should also update the [filtering lesson](https://cloud.archivesunleashed.org/derivatives/text-filtering) to note that we have _some_ of this already built in.

I'll do first pass and can flip it to @SamFritz for second set of eyes.

**Comment by ianmilligan1** [comment]
Once it's pushed to the main site early next week, @SamFritz, I think the only screenshot to update is this one. Probably best if you take the lead on it as it uses your account.

![auk_output-a4ab96d07fb77ad17733e194da0e42d4afe256004dab5814796a7dcdcd4701f6](https://user-images.githubusercontent.com/3834704/47943056-99759e00-deb1-11e8-834f-98812a335eaf.png)

**Comment by SamFritz** [comment]
Sounds good!

**Comment by SamFritz** [comment]
updated screenshot to include new button --> to replace image "AUK_output.png": 
![screen shot 2018-11-09 at 1 44 47 pm](https://user-images.githubusercontent.com/7362321/48281842-e57e9080-e425-11e8-88eb-c04557b8689e.png)
