### ISSUE TITLE
Survey Users for Interface + Derivative Feedback

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/auk#215]
As discussed in our project leadership channel, we should survey our users about their use of the Archives Unleashed Cloud. As users have opted into occasional e-mail communication from us as part of the operations of the system, this can come out of our users table. 

The survey should happen in January after the dust of the holiday season has settled.

Some things that we'll want to learn:
* Are there any new derivatives that users would want (filtering text by year, for example, or something to do with networks)?
* Are there any parts of the interface that are unclear? How can we improve our usability?

Some suggestions for structuring it:
* Maybe explicitly ask "What's one thing that you would change with the Archives Unleashed Cloud?" so we can get some constructive feedback even from people who are happy with the platform as is.

**Comment by SamFritz** [comment]
Created google doc to use as initial brainstorming/editing of questions we'd like to use in [AUK User Survey](https://docs.google.com/document/d/15RHJ5HSNQMGui2UW8D3hTcHInl3A5gbZy2yiqiObi8A/edit)

**Comment by ianmilligan1** [comment]
Survey is finalized and will be sent out next week. Any suggestions for feedback will materialize in separate tickets.
