### ISSUE TITLE
Feature Request: show when a collection was analyzed in the interface

### ISSUE THREAD

**Issue by machawk1** [archivesunleashed/auk#234]
**Is your feature request related to a problem? Please describe.**
The interface shows a boolean value (i.e., `Yes` if Analyzed by AUK, `No` otherwise) of whether a collection has been analyzed. Collections may change contents. It would be informative to give more information of _when_ the collection was analyzed.

**Describe the solution you'd like**
Show a date, hash, etc. to give an indication of the state of a collection when it was analyzed.

**Additional context**
I have a collection that I am using AUK to analyze but plan on adding to it as more relevant seeds come about. Iterating on AUK and the Archive-It interface will provide better insight on the collection's contents.

**Comment by ianmilligan1** [comment]
Thanks @machawk1 – this is a good idea! We're just going to chat about it as a team.

Appreciate your engagement with the project. 😄
