### ISSUE TITLE
Export network as PNG/JPEG high resolution

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/auk#255]
**Is your feature request related to a problem? Please describe.**
Feature request: if network image in collection page can be downloaded as a high resolution PNG/JPEG. This could allow users ability to incorporate basic network graph into presentations/posters without having to jump over to another tool.

**Describe the solution you'd like**
@greebie will take a look at whether this could be possible. Looking at snapshot feature

**Comment by greebie** [comment]
Solution will be something like this:

(on click):
`getElementsByClassName ("sigma-scene")[0].toDataURL('image/png')`
"Do you want to save the file?" alert.
Then download the file.
I am going to assume that the correct default is 300 dpi (print quality)

I can imagine some UI being helpful here, as I can imagine people wanting to right-click.  When you do that you get a "save image" request, but it does a sigma save image thing which is not that helpful, frankly (try it and be disappointed).

**Comment by ianmilligan1** [comment]
Thanks for this @greebie. So would this be a button or something in the sigma frame?
