### ISSUE TITLE
Home Page - slider images (update)

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/auk#261]
**Describe the solution you'd like**
Based on user feedback and team discussion, it would be great to update network image on home page (slider) to visualize AUK collection we've analyzed. The Nova Scotia Government collection has a fairly large network. 

Visual Specs (if possible let's try and keep same feel as current network diagram)
- black background
- labels
- indegree
- slider image: 1920x800

**Comment by SamFritz** [comment]
I've used Gephi to create a basic layout of the NS gov collection network - it's also given me a chance to learn more about Gephi through hands on experience. The only issue I'm having is exporting the final network as a png, but this is what I've managed to create so far. 

Labels really clutter the image - I'll see if I can highlight a few specific nodes :) 

![screen shot 2019-02-05 at 11 07 27 pm](https://user-images.githubusercontent.com/7362321/52320078-39ecca00-299b-11e9-8cdf-a491f3c44eb3.png)

**Comment by ianmilligan1** [comment]
Looks great @SamFritz! Ping me on Slack if you've got any questions re: exporting a high-res version (or we can look at this on Friday too when we're in the same physical space).

**Comment by SamFritz** [comment]
This issue has now been resolved; slide image updated. 

Closing issue with implementation via commit [`3a51eac`](/archivesunleashed/auk/commit/3a51eaca7a3842d0cc198f395d7a3de3d1a6b3ef)
