### ISSUE TITLE
Closing Cloud (2020)

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/auk#457]
As we move towards decommissioning Cloud in June 2020, some things we will need to think about and plan for conveying message and notice to users:
- [x] Banner on Cloud site - notice that site will be decommissioned, click for more details
- [x] Static page with short explanation of what's happening (Cloud is being shut down, but service will be continued in AI, see more)
- [ ] Notice on AU.org (https://archivesunleashed.org/cloud/)
- [x] Do we need anything within the user's account? Banner doesn't carry into this space, so perhaps a reminder note above the Collections table?

Notice Roll out:
- Email users @ 120 (March 1) /30 (June 1) day marks and final week?
- Post notices on Cloud site (banners and static page) @ 120 (March 1) or 90 (April 1) day mark?

Opening ticket for further discussion as we move along.

**Comment by ianmilligan1** [comment]
Depending on thoughts, I'm happy to implement this (banner notices + static page).
